# The URL the site will be built for
base_url = "https://emmatyping.dev"

title = "emmatyping"

description = "Emma's website and interblag"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "terminimal"

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "visual-studio-dark"

[extra]
accent_color = "blue"
background_color = "dark"

logo_text = "Emma's Blog"
logo_home_link = "/"

author = "Emma Harper Smith"

# Put all your custom variables here
menu_items = [
    {url= "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/about/me", name = "About"},
    {url = "$BASE_URL/about/contact", name = "Contact"},
    {url = "https://github.com/emmatyping", name = "Github", newtab = true},
    {url = "https://hachyderm.io/@emmatyping", name = "Mastodon", newtab = true},
    {url = "https://bsky.app/profile/emmatyping.dev", name = "BlueSky", newtab = true},
]
